# Generated by Django 3.2.4 on 2021-06-17 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDonation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_no', models.BigIntegerField(blank=True)),
                ('med', models.CharField(max_length=100)),
                ('md', models.DateField(default=datetime.date.today)),
                ('ed', models.DateField(default=datetime.date.today)),
                ('content', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
