# Generated by Django 3.2.4 on 2021-06-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_medicinedonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinedonation',
            name='content',
        ),
    ]
